// Script to handle initial mission briefings
// General guidelines would be to include briefings for the following
// Situation, Mission, and Assets
// Briefings are listed in the opposite order that they are written below. New diaryRecords are always placed at the top of the list.
// https://community.bistudio.com/wiki/createDiaryRecord


player createDiaryRecord ["Diary", ["Assets", "Your assets for this mission are: <br /> -2x Hummingbird Helicopters for light recon and fast insertion. <br /> -8x Police Offroad Pickups"]];
player createDiaryRecord ["Diary", ["Mission", "We've got hostage and bomb situations at three locations: the Tanoa Sugar Company, Comms Alpha, and the Red Spring Surface Mine. Each location has civilians being held hostage as well as explosive charges placed. We estimate there are between 3-6 charges at each location but we can't be sure. Judging by the terrorists demands and their threats of premature detonation or execution, we're assuming we'll have two hours at most before negotiations break down and they kill the civilians and blow the charges. Once you insert at a location, the terrorists there will most likely detonate the charges and execute their hostages sooner, so plan your insertion and move fast. Our informant is being held by ISIS at a small encampment, if we rescue him then we'll get more detailed information on the different locations. While our enemy is mostly just infantrymen with rifles, don't underestimate them and be ready for anything. <br />We've set up aid stations just outside each of the combat zones, escort the civilians there using your cable ties, the aid stations are marked on your map in blue. <br />To disarm the charges, have your EOD specialist defuse them with their defusal kit. It's not necessary to recover the charges, we just want them to be disabled."]];
player createDiaryRecord ["Diary", ["Situation", "Alright men, the situation is bad, and it's going to get a lot worse very soon. While president Duterte was making a public speech to reaffirm his plans to defeat the cartels and get revenge on ISIS for Marawi, militants stormed multiple locations and taken civilian hostages. They have also placed explosive charges around the locations and are threatening to detonate them if Duterte doesn't cave to their demands. We've been called in on short notice, so our intel is limited, however we did have a mole in their organisation. His cover was blown and he's now being held at a small outpost by ISIS fighters, if we rescue him he could provide some much needed intel."]];
player createDiaryRecord ["Diary", ["The Story So Far", "After killing notorious drug kingpin Tony Pajamas, our SWAT team became national icons. Following his death, Tony's cartel has torn itself apart trying to fill the power vacuum, and we've made countless arrests. Our team even has a nickname now: Duterte's Devils."]];