// Script to handle initial mission briefings
// General guidelines would be to include briefings for the following
// Situation, Mission, and Assets
// Briefings are listed in the opposite order that they are written below. New diaryRecords are always placed at the top of the list.
// https://community.bistudio.com/wiki/createDiaryRecord

player createDiaryRecord ["Diary", ["Assets", "Your assets for this operation include: <br />-One hummingbird, for fast insertion and recon. <br />-Two AN-2 Darter quadcopters, for recon <br />-Multiple police offroad trucks, for transport"]];
player createDiaryRecord ["Diary", ["Mission", "Right, since you're still here, you're evidently willing to undertake the mission. We've been tasked with eliminating three traitors who have faked testimony, documents, and other evidence in an attempt to get our president impeached and thrown in jail. One is an accountant who has faked financial records to accuse Duterte of embezzlement, another is a former member of Duterte's security detail bribed into accusing him of treason and giving false testimony, and the third is a foreign journalist who has doctored various photos to support the previous fake evidence. We know they are all being held in safe houses on the southwestern islands, but which safe houses we do not know. We must raid the safe houses, terminate the traitors, seize the false evidence, and then plant drugs on the bodies to discredit and implicate those in parliament who wish to betray our nation. To get the drugs, we will kill two birds with one stone: there is a small drug hideaway on the western side of the island, which we will raid and destroy. We must act with haste, in roughly two hours a convoy will arrive to bring the traitors to the southern airport in order to ferry them out of country. If they escape, our mission will be a failure. After the traitors are dealt with, a helicopter will extract your team.<br /> Good luck men."]];
player createDiaryRecord ["Diary", ["A Word From The President", "My friends, honourable officers of justice. You've done an amazing job in cleaning up the drug running scum of the Tony Pajamas cartel, and were integral in defending the people of the Philippines from the Islamic terrorist group ISIS. You've already risen far above the call of duty, and for that reason I believe you are men much like myself, men who will do anything to protect the people of our nation. I've said before that I'm willing to go to hell so that the people of the Philippines may live in paradise. Today, I ask you to join me in that pledge. There are members of parliament who would see me removed from office, and undo all the good we have done together. They have fabricated evidence against me and bribed former friends to turn on me, and they now believe they have enough 'evidence' to impeach me. A military colonel is among those who wishes to see me removed, and the traitors are being guarded by our very own army. While the soldiers guarding the traitors are innocent, there is no time for a more subtle solution. As much as it pains me so, I must ask you to kill your countrymen for the sake of our people. If any man does not wish to partake in this mission, I will not judge them for it, nor will they be punished in any way."]];
player createDiaryRecord ["Diary", ["The Story So Far", "Our SWAT team rose to prominence during a wave of drug crackdowns shortly after Duterte began his crusade on drugs. During the early raids, we neutralised Tony Pajamas, a prominent drug cartel kingpin. Shortly after he was out of the picture, many smaller cartels tore each other apart trying to fill the power vacuum, with our team carrying out dozens of raids in the chaos. We became known as 'Duterte's Devils' and become national heroes when a group of ISIS militants planted bombs and took dozens of hostages in a major terrorist action. Our team managed to minimise the damage and loss of life, causing our SWAT unit to receive personal recognition and citation from Duterte himself."]];